### ISSUE TITLE
[BUG] npm ERR! notarget No matching version found for aframe-typescript-toolkit@0.0.17

### ISSUE THREAD

**Issue by ResourceHog** [olioapps/aframe-typescript-toolkit#12]
To recreate this issue.

`aframe-typescript-toolkit`

select system

cd to created system directory.

`npm install`

`npm ERR! notarget No matching version found for aframe-typescript-toolkit@0.0.17`

editing the package.json to use version 0.0.16 fixes this error however I feel like this is undesirable behavior. Either 17 hasn't been uploaded or 17 wasn't supposed to be generated.

**Comment by rachoac** [comment]
Thanks, I will take a look

**Comment by rachoac** [comment]
@ResourceHog I published an update to the toolkit, 0.0.19 fixing the issue for new projects created by the toolkit. Version 0.0.18 was referencing a broken version of the toolkit (0.0.17).
