### ISSUE TITLE
[BUG] test/test/node_modules/three/src/Three"' has no exported member 'VREffect'

### ISSUE THREAD

**Issue by ResourceHog** [olioapps/aframe-typescript-toolkit#13]
create a fresh system then npm install
npm run build

then this error should appear

ERROR in [at-loader] ./node_modules/@types/aframe/index.d.ts:254:17 
TS2694: Namespace '"path/to/project/test/test/node_modules/three/src/Three"' has no exported member 'VREffect'

**Comment by ResourceHog** [comment]
@type/three in nodemodules clearly has this class in it....

**Comment by ResourceHog** [comment]
version of @type/aframe must be 0.7.2

**Comment by rachoac** [comment]
@ResourceHog this has been fixed by version 0.0.20 of the aframe-typescript-toolkit
